Repository netbox-community/devicetype-library, pull requests merged in 2022-12, with the labels that each got.

#983 Add Cisco ASR-920-12SZ-D
  device-types/Cisco/ASR-920-12SZ-D.yaml
Labels: Accepted

#984 Add Cisco ASR-920-12CZ-A
  device-types/Cisco/ASR-920-12CZ-A.yaml
Labels: Accepted

#986 Add Cisco N540-28Z4C-SYS-D
  device-types/Cisco/N540-28Z4C-SYS-D.yaml
Labels: status: gathering feedback

#1000 Added airflow tag to WTI devices
  device-types/WTI/CPM-1600-1-EC.yaml
  device-types/WTI/CPM-1600-1-ECAM.yaml
  device-types/WTI/CPM-800-1-A-VZW.yaml
  device-types/WTI/CPM-800-1-A.yaml
  device-types/WTI/CPM-800-1-AM.yaml
  device-types/WTI/CPM-800-1-E.yaml
  device-types/WTI/CPM-800-1-EA.yaml
  device-types/WTI/CPM-800-1-ECA.yaml
  device-types/WTI/CPM-800-2-A-VZW.yaml
  device-types/WTI/CPM-800-2-A.yaml
  device-types/WTI/CPM-800-2-AM.yaml
  device-types/WTI/CPM-800-2-E.yaml
  device-types/WTI/CPM-800-2-EA.yaml
  device-types/WTI/DSM-24NM-DP.yaml
  device-types/WTI/DSM-24NM-E.yaml
  device-types/WTI/DSM-24NM.yaml
  device-types/WTI/DSM-40NM-DP.yaml
  device-types/WTI/DSM-40NM-E.yaml
  device-types/WTI/DSM-40NM.yaml
  device-types/WTI/DSM-8NM-DP.yaml
  device-types/WTI/DSM-8NM-E.yaml
  device-types/WTI/DSM-8NM.yaml
  device-types/WTI/NBB-20VD20-1.yml
  device-types/WTI/NPS-8H20-ATS-1.yml
  device-types/WTI/REM-0R4-1-E.yaml
  device-types/WTI/REM-0R4-1-N.yaml
  device-types/WTI/REM-0R4-1-NE.yaml
  device-types/WTI/REM-0R4-1-W.yaml
  device-types/WTI/REM-0R4-1-WE.yaml
  device-types/WTI/REM-0R4-1.yaml
  device-types/WTI/REM-0R4-2-E.yaml
  device-types/WTI/REM-0R4-2-N.yaml
  device-types/WTI/REM-0R4-2-NE.yaml
  device-types/WTI/REM-0R4-2-W.yaml
  device-types/WTI/REM-0R4-2-WE.yaml
  device-types/WTI/REM-0R4-2.yaml
  device-types/WTI/REM-4R0-E.yaml
  device-types/WTI/REM-4R0-NE.yaml
  device-types/WTI/REM-4R0-W.yaml
  device-types/WTI/REM-4R0-WE.yaml
  device-types/WTI/REM-4R0.yaml
  device-types/WTI/REM-4R4-1-E.yaml
  device-types/WTI/REM-4R4-1-N.yaml
  device-types/WTI/REM-4R4-1-NE.yaml
  device-types/WTI/REM-4R4-1-W.yaml
  device-types/WTI/REM-4R4-1-WE.yaml
  device-types/WTI/REM-4R4-1.yaml
  device-types/WTI/REM-4R4-2-E.yaml
  device-types/WTI/REM-4R4-2-N.yaml
  device-types/WTI/REM-4R4-2-NE.yaml
  device-types/WTI/REM-4R4-2-W.yaml
  device-types/WTI/REM-4R4-2-WE.yaml
  device-types/WTI/REM-4R4-2.yaml
  device-types/WTI/VMR-16HD20-2.yaml
  device-types/WTI/VMR-8H20-ATS-1.yaml
  device-types/WTI/VMR-8H20-ATS-2.yaml
  device-types/WTI/VMR-8HS20-1.yaml
  device-types/WTI/VMR-8HS20-2.yaml
  device-types/WTI/VMR-HD4D16H.yaml
Labels: Accepted

#935 Add Huawei CloudEngine S5732-H48XUM2CC model + PSU + FAN
  device-types/Huawei/S5732-H48XUM2CC.yaml
  module-types/Huawei/FAN-031A-B.yaml
  module-types/Huawei/PAC1000S56-CB.yaml
Labels: Accepted

#987 Adding the UniFi Dream Machine (non-pro)
  device-types/Ubiquiti/UDM-Pro.yaml
  device-types/Ubiquiti/UDM.yaml
Labels: status: revisions needed

#1002 Added APC SMX3000HVNC UPS and related battery pack.
  device-types/APC/SMX120BP.yaml
  device-types/APC/SMX3000HVNC.yaml
Labels: Accepted

#975 TEG-S16Dg Initial Commit
  device-types/TrendNet/TEG-S16Dg.yaml
Labels: Accepted

#1001 Added Wall boxes with 2, 3, 4 and 6 UTP plugs.
  device-types/Generic/wall-box-2-utp.yaml
  device-types/Generic/wall-box-3-utp.yaml
  device-types/Generic/wall-box-4-utp.yaml
  device-types/Generic/wall-box-6-utp.yaml
Labels: question, status: revisions needed

#1009 Mikrotik RB750Gr3 added more Details to existing Device-Type
  device-types/MikroTik/RB750Gr3.yaml
Labels: Accepted

#1010 Updating Mikrotik RB960PGS Device Type with more Details
  device-types/MikroTik/RB960PGS.yaml
Labels: Accepted

#1011 Added RB5009UPr+S+IN
  device-types/MikroTik/RB5009UPr+S+IN.yaml
Labels: Accepted

#1008 Added RB5009UG+S+IN
  device-types/MikroTik/RB5009UG+S+IN.yaml
Labels: Accepted

#1012 Created TP-Link T2600G-28TS Switch Device-Type
  device-types/TP-Link/T2600G-28TS.yaml
Labels: Accepted

#1007 Cisco 2821
  device-types/Cisco/ISR2821.yaml
  module-types/Cisco/AIM-VPN_EPII-PLUS.yaml
  module-types/Cisco/PVDM2-64.yaml
  module-types/Cisco/VIC2-4FXO.yaml
Labels: Accepted

#1005 Create TL-SG105E.yaml
  device-types/TP-Link/TL-SG105E.yaml
Labels: Accepted

#1004 Create TL-SG108E.yaml
  device-types/TP-Link/TL-SG108E.yaml
Labels: Accepted

#1006 Huawei s5700
  device-types/Huawei/S5731-S24T4X.yaml
  device-types/Huawei/S5735-L24P4X-A1.yaml
  module-types/Huawei/FAN-023A-B.yaml
  module-types/Huawei/PAC600S12-DB.yaml
Labels: Accepted

#1013 Create APC UPS SMT3000RMI2UC
  device-types/APC/SMT3000RMI2UC.yaml
Labels: Accepted

#1014 Update Airflow for ICX 7150-C12P-2x10GR
  device-types/Ruckus/icx7150-c12p-2x10gr.yaml
Labels: Accepted

#1015 Create Ruckus icx-7150-48p-4x10g.yaml Switch
  device-types/Ruckus/icx-7150-48p-4x10g.yaml
Labels: Accepted

#949 Add CryptoPro manufacturer. NGATE-320 and NGATE-600 models.
  device-types/CryptoPro/NGATE-320.yaml
  device-types/CryptoPro/NGATE-600.yaml
Labels: Accepted

#1016 Updated Typos and added Details for AVM FRITZ!Box 7590
  device-types/AVM/7590.yaml
Labels: Accepted

#1018 Update RB2011iL-RM.yaml with PoE and other Details
  device-types/MikroTik/RB2011iL-RM.yaml
Labels: Accepted

#974 Adding Fortinet FortiGate 600F and 601F devices
  device-types/Fortinet/FG-600F.yaml
  device-types/Fortinet/FG-601F.yaml
Labels: status: revisions needed
