Repository netbox-community/devicetype-library, pull requests merged in 2023-01, with the labels that each got.

#1019 feat: add AVM Fritzbox 7530
  device-types/AVM/7530.yaml
Labels: Accepted

#933 Check Point: Add SG23800 and add/move modules
  device-types/Check Point/SG23800.yaml
  module-types/Check Point/2-10FSR-BP-B.yaml
  module-types/Check Point/4-10F-C.yaml
  module-types/Check Point/4-1C-BP-B.yaml
  module-types/Check Point/4-1F-C.yaml
  module-types/Check Point/8-1C-C.yaml
Labels: Accepted

#957 add unifi USW-Lite-16-PoE
  device-types/Ubiquiti/USW-Lite-16-PoE.yaml
Labels: Accepted

#939 Create CRS310-1G-5S-4S+IN.yaml
  device-types/MikroTik/CRS310-1G-5S-4S+IN.yaml
Labels: stale

#955 Add Tripp-Lite SMART2200CRMXL device type and SNMPWEBCARD module type
  device-types/TrippLite/SMART2200CRMXL.yaml
  module-types/TrippLite/SNMPWEBCARD.yaml
Labels: status: revisions needed

#883 Add HPE 5510 48G POE and non-POE
  device-types/HPE/5510-48G-4SFPP-HI.yaml
  device-types/HPE/5510-48G-POEP-4SFPP-HI.yaml
  module-types/HPE/X361.yaml
  module-types/HPE/X362.yaml
Labels: status: revisions needed

#936 Added Cisco UCS FI6454 Device and the IOM-2408 Module
  device-types/Cisco/UCS-FI-6454.yaml
  module-types/Cisco/UCS-IOM-2408.yaml
Labels: Accepted

#952 Add EdgeRouter 10X, 4, 6P, 8, 3
  device-types/Ubiquiti/ER-10X.yaml
  device-types/Ubiquiti/ER-4.yaml
  device-types/Ubiquiti/ER-6P.yaml
  device-types/Ubiquiti/ER-8.yaml
  device-types/Ubiquiti/ERLite-3.yaml
Labels: Accepted

#976 Create S5720-28X-LI-24S-DC.yaml
  device-types/Huawei/S5720-28X-LI-24S-DC.yaml
Labels: Accepted

#1025 #979 @basictheprogramm synology ds418 fix
  .gitignore
  device-types/Synology/DS418.yaml
Labels: Accepted

#1033 Update Meraki-MX250.yaml
  device-types/Cisco/Meraki-MX250.yaml
Labels: Accepted

#1032 Create Cisco Meraki-MX450.yaml
  device-types/Cisco/Meraki-MX450.yaml
Labels: Accepted

#1031 Create RAD ETX-2i-10G.yaml
  device-types/RAD/ETX-2i-10G.yaml
Labels: status: revisions needed

#1026 Adding dependabot & updating reqirements
  .github/dependabot.yml
  .github/workflows/validation.yml
  .pre-commit-config.yaml
  requirements.txt
Labels: Accepted

#1035 Eaton PSU, EBM and PDUs
  device-types/Eaton/9PX5KIRTN.yaml
  device-types/Eaton/9PXEBM180.yaml
  device-types/Eaton/CBL2OUT32.yaml
  device-types/Eaton/ESWB05.yaml
  device-types/Eaton/ESWB22.yaml
Labels: Accepted

#1037 PowerVault ME4024 Fix
  device-types/Dell/PowerVault_ME4024.yml
  module-types/Dell/3PD98.yaml
  module-types/Dell/49H29.yaml
Labels: Accepted

#1038 Dell 49H29 Serial Name Fix
  module-types/Dell/49H29.yaml
Labels: Accepted

#1040 Addition of NEC UNIVERGE IX Series
  device-types/NEC/UNIVERGE-IX2106.yaml
  device-types/NEC/UNIVERGE-IX2107.yaml
  device-types/NEC/UNIVERGE-IX2215.yaml
  device-types/NEC/UNIVERGE-IX2235.yaml
  device-types/NEC/UNIVERGE-IX2310.yaml
Labels: Accepted

#1039 Addition of Ubiquiti Switch Pro Aggregation
  device-types/Ubiquiti/USW-Pro-Aggregation.yaml
  schema/components.json
Labels: Accepted

#1043 Dell ME4024 Fixes
  device-types/Dell/PowerVault_ME4024.yml
Labels: Accepted

#938 Ubiquiti devices
  device-types/Ubiquiti/UAP-IW-HD.yaml
  device-types/Ubiquiti/UC-CK.yaml
  device-types/Ubiquiti/UCK-G2-PLUS.yml
  device-types/Ubiquiti/UCK-G2.yml
  device-types/Ubiquiti/UDM-Pro.yaml
  device-types/Ubiquiti/USP-RPS.yaml
  device-types/Ubiquiti/USW-24-PoE.yaml
  device-types/Ubiquiti/USW-Lite-8-PoE.yaml
  device-types/Ubiquiti/USW-Pro-24-PoE.yaml
  device-types/Ubiquiti/USW-Pro-48-PoE.yaml
  device-types/Ubiquiti/USW-Pro-48.yaml
Labels: question, status: revisions needed

#894 Addition of Cisco 8201-32FH device-type router model
  device-types/Cisco/8201-32FH.yaml
  device-types/Cisco/8202-32FH-M.yaml
  device-types/Cisco/ASR-9001.yaml
  device-types/Cisco/ASR-9902.yaml
  device-types/Cisco/ASR-9903.yaml
  device-types/Cisco/N540-ACC-SYS.yaml
  device-types/Ericsson/R6672.yml
  module-types/Cisco/A99-RP-F.yaml
  module-types/Cisco/A9903-20HG-PEC.yml
  module-types/Cisco/ASR-9902-FAN.yaml
  module-types/Cisco/ASR-9903-FAN.yaml
  module-types/Cisco/N540-FAN.yaml
  module-types/Cisco/N540-PWR400-A.yaml
  module-types/Cisco/PSU2KW-ACPI.yaml
  module-types/Cisco/PWR-1.6KW-AC.yaml
Labels: Accepted

#1044 Patch 3
  device-types/HPE/V1910-48G.yaml
Labels: Accepted

#944 Added Canon manufacturer and some iR-ADV C3xxx devices
  device-types/Canon/IR-ADV-C3520.yaml
  device-types/Canon/IR-ADV-C3530-III.yaml
  device-types/Canon/IR-ADV-C3530.yaml
  device-types/Canon/IR-ADV-C3720.yaml
Labels: Accepted

#1047 Add Cisco 9200 module bays
  module-types/Cisco/C9200-NM-2Q.yaml
  module-types/Cisco/C9200-NM-2Y.yaml
  module-types/Cisco/C9200-NM-4G.yaml
  module-types/Cisco/C9200-NM-4X.yaml
Labels: Accepted

#1050 Create Dell PowerEdge_1950.yaml Device Type
  device-types/Dell/PowerEdge_1950.yaml
Labels: Accepted

#1051 add synology e10m20-t1.yaml
  module-types/Synology/E10M20-T1.yaml
Labels: Accepted

#1048 Create CRS226-24G-2S+RM.yaml Device Type model
  device-types/MikroTik/CRS226-24G-2S+RM.yaml
Labels: Accepted

#1052 Added stack ports
  device-types/Cisco/WS-C3750-48TS-S.yaml
Labels: question, In Review

#1045 Add APC SMT2200RMI2UNC
  device-types/APC/SMT2200RMI2UNC.yaml
Labels: Accepted

#1061 Added weight to device and module types
  README.md
  schema/components.json
  schema/devicetype.json
  schema/moduletype.json
Labels: In Review

#1024 Add Schema Interface Types & Correctly Identify Adapters (AT FS Series)
  module-types/Allied Telesis/FS201.yaml
  module-types/Allied Telesis/FS202.yaml
  module-types/Allied Telesis/FS232-1.yaml
  module-types/Allied Telesis/FS232-2.yaml
  module-types/Allied Telesis/FS232.yaml
  module-types/Allied Telesis/FS238A-1.yaml
  module-types/Allied Telesis/FS238B-1.yaml
  schema/components.json
Labels: Accepted

#1062 add Lenovo Servers SR530/SR550/X3250M6 and fix SR650
  device-types/Lenovo/SR530.yaml
  device-types/Lenovo/SR550.yaml
  device-types/Lenovo/SR650.yaml
  device-types/Lenovo/system_x3250_M6.yaml
Labels: Accepted

#1069 Weight Validation Fix
  schema/components.json
Labels: Accepted

#1046 Added Mellanox, NEC, Netgear, and Yamaha switches/routers
  device-types/Mellanox/SN3700.yml
  device-types/Mellanox/SN4600.yml
  device-types/Mellanox/SN4600C.yml
  device-types/Mellanox/SN4700.yml
  device-types/NEC/UNIVERGE-IX2015.yaml
  device-types/NEC/UNIVERGE-IX2025.yaml
  device-types/NEC/UNIVERGE-IX2105.yaml
  device-types/NEC/UNIVERGE-IX2215.yaml
  device-types/NEC/UNIVERGE-IX2235.yaml
  device-types/Netgear/GS116.yaml
  device-types/Netgear/GS116E.yaml
  device-types/Netgear/JGS524.yaml
  device-types/YAMAHA/SWX2110-16G.yaml
  device-types/YAMAHA/SWX2110-5G.yaml
  device-types/YAMAHA/SWX2110-8G.yaml
  device-types/YAMAHA/SWX2110P-8G.yaml
  device-types/YAMAHA/SWX2210-16G.yaml
  device-types/YAMAHA/SWX2210-24G.yaml
  device-types/YAMAHA/SWX2210-8G.yaml
  device-types/YAMAHA/SWX2210P-10G.yaml
  device-types/YAMAHA/SWX2210P-18G.yaml
  device-types/YAMAHA/SWX2210P-28G.yaml
  device-types/YAMAHA/SWX2220-10NT.yaml
  device-types/YAMAHA/SWX2221P-10NT.yaml
  device-types/YAMAHA/SWX2310-10G.yaml
  device-types/YAMAHA/SWX2310-18GT.yaml
  device-types/YAMAHA/SWX2310-28GT.yaml
  device-types/YAMAHA/SWX2310-52GT.yaml
  device-types/YAMAHA/SWX2310P-10G.yaml
  device-types/YAMAHA/SWX2310P-18G.yaml
  device-types/YAMAHA/SWX2310P-28GT.yaml
  device-types/YAMAHA/SWX2320-16MT.yaml
  device-types/YAMAHA/SWX2322P-16MT.yaml
  device-types/YAMAHA/SWX3100-10G.yaml
  device-types/YAMAHA/SWX3100-18GT.yaml
  device-types/YAMAHA/SWX3200-28GT.yaml
  device-types/YAMAHA/SWX3200-52GT.yaml
  device-types/YAMAHA/SWX3220-16MT.yaml
  device-types/YAMAHA/SWX3220-16TMs.yaml
Labels: Accepted

#1074 Create FS FMU-MC042733 CWDM Module
  device-types/FS/FMU-MC042733.yaml
Labels: Accepted

#1075 Create FS FMU-MC084761EM3.yaml CWDM
  device-types/FS/FMU-MC084761EM3.yaml
Labels: In Review

#1076 Create GS5104-1471-EC.yaml
  device-types/ghipsystems/GS5104-1471-EC.yaml
Labels: Accepted

#1072 Adding equipment from the manufacturer DATACOM.
  device-types/Datacom/DM4610-OLT-4GPON+4GX+2XS.yaml
  module-types/Datacom/FAN_OLT-DM4610.yaml
  module-types/Datacom/PSU-120-AC_OLT-DM4610.yaml
  module-types/Datacom/PSU-120-DC_OLT-DM4610.yaml
Labels: Accepted
