Repository netbox-community/devicetype-library, pull requests merged in 2023-03, with the labels that each got.

#1162 Add QNAP TS-453D
  device-types/QNAP/TS-453D.yml
Labels: Accepted

#1160 EnGenius
  device-types/EnGenius/EWS1200-28TFP.yaml
  device-types/EnGenius/EWS360AP.yaml
  device-types/EnGenius/EWS5912FP.yaml
Labels: Accepted

#1163 Update N9K-C9372TX.yaml
  device-types/Cisco/N9K-C9372TX.yaml
Labels: Accepted

#1161 Added FS S3150-8T2FP
  device-types/FS/S3150-8T2FP.yaml
Labels: status: revisions needed

#1167 Add HPE ProLiant DL365 Gen11
  device-types/HPE/ProLiant-DL365-Gen11.yaml
Labels: Accepted

#1150 added some FlexNetwork-5130
  device-types/HPE/FlexNetwork-5130-24G-4SFP+-EI.yml
  device-types/HPE/FlexNetwork-5130-48G-4SFP+-EI.yml
  device-types/HPE/FlexNetwork-5130-48G-4SFPP-HI.yml
  device-types/HPE/FlexNetwork-5130-48G-PoEP-4SFPP-HI.yml
Labels: Accepted

#1119 Add Adtran NetVanta 4660
  device-types/Adtran/NV4660.yaml
Labels: Accepted

#1170 Cisco SPA112
  device-types/Cisco/SPA112.yaml
Labels: Accepted

#1138 Create Huawei CE8800 series
  device-types/Huawei/CE8850-64CQ-EI.yaml
  device-types/Huawei/CE8861-4C-EI.yaml
  module-types/Huawei/CE88-D24S2CQ.yaml
  module-types/Huawei/CE88-D8CQ.yaml
Labels: status: accepted

#1179 Add FS S5860-20SQ
  device-types/FS/S5860-20SQ.yaml
  module-types/FS/SPSM-C150WAC.yaml
Labels: status: revisions needed

#1180 Add Intel H2312XXKR2 Blade Chassis
  device-types/Intel/H2312XXKR2.yaml
Labels: status: accepted

#1183 Added and fixed several Avocent device types
  device-types/Avocent/ACS8008SAC-400.yaml
  device-types/Avocent/ACS8016SAC-400.yaml
  device-types/Avocent/ACS8032SAC-400.yaml
  device-types/Avocent/ACS8048SAC-400.yaml
Labels: status: accepted

#1174 Improved comments in ubiquiti er-x
  device-types/Ubiquiti/ER-X.yaml
Labels: status: accepted

#1191 New Device: Fortinet Fortigate 100EF
  device-types/Fortinet/FG-100EF.yaml
Labels: status: accepted

#1193 Add Mikrotik & Zyxel device types
  device-types/MikroTik/CRS109-8G-1S-2HnD-IN.yaml
  device-types/MikroTik/RB951Ui-2nD.yaml
  device-types/Zyxel/PMG1005-T20B.yaml
Labels: status: accepted

#1165 #1164 - Implementation of IEEE 802.3az
  schema/components.json
Labels: status: accepted

#1195 March File Cleanup
  device-types/FS/S5860-20SQ.yaml
  device-types/MikroTik/CRS109-8G-1S-2HnD-IN.yaml
  device-types/MikroTik/RB1200.yaml
  device-types/MikroTik/RB2011iL-IN.yaml
  device-types/MikroTik/RB4011iGS+RM.yaml
  device-types/MikroTik/RB941-2nD-TC.yaml
  device-types/MikroTik/RB951Ui-2nD.yaml
  device-types/Zyxel/FMG3005-R20A.yaml
  device-types/Zyxel/PMG1005-T20B.yaml
Labels: status: accepted

#1197 Update Datto Switch PoE to `type2-ieee802.3az`
  device-types/Datto/DSW100-24P-4X.yaml
  device-types/Datto/DSW100-84P-4X.yaml
  device-types/Datto/DSW100-8P-2G.yaml
  device-types/Datto/DSW250-8P-2X.yaml
Labels: status: accepted

#1198 Create Ruckus R350 WiFi Access Point
  device-types/Ruckus/r350.yaml
Labels: status: accepted

#1189 Contributes 6 new device types for Nokia SR Linux product line
  device-types/Nokia/7220-IXR-D1.yaml
  device-types/Nokia/7220-IXR-D2.yaml
  device-types/Nokia/7220-IXR-D2L.yaml
  device-types/Nokia/7220-IXR-D3.yaml
  device-types/Nokia/7220-IXR-D3L.yaml
  device-types/Nokia/7220-IXR-H3.yaml
  module-types/Nokia/FAN-7220-IXR-D1-B2F.yaml
  module-types/Nokia/FAN-7220-IXR-D1-F2B.yaml
  module-types/Nokia/FAN-7220-IXR-D2-B2F.yaml
  module-types/Nokia/FAN-7220-IXR-D2-F2B.yaml
  module-types/Nokia/FAN-7220-IXR-D2L-B2F.yaml
  module-types/Nokia/FAN-7220-IXR-D2L-F2B.yaml
  module-types/Nokia/FAN-7220-IXR-D3-B2F.yaml
  module-types/Nokia/FAN-7220-IXR-D3-F2B.yaml
  module-types/Nokia/FAN-7220-IXR-D3L-B2F.yaml
  module-types/Nokia/FAN-7220-IXR-D3L-F2B.yaml
  module-types/Nokia/FAN-7220-IXR-H3-B2F.yaml
  module-types/Nokia/FAN-7220-IXR-H3-F2B.yaml
  module-types/Nokia/PS-7220-IXR-D1-AC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-D1-AC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-D1-DC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-D1-DC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-D2D3-AC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-D2D3-AC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-D2D3-DC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-D2D3-DC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-D2LD3L-AC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-D2LD3L-AC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-D2LD3L-DC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-D2LD3L-DC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-H3-AC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-H3-AC-F2B.yaml
  module-types/Nokia/PS-7220-IXR-H3-DC-B2F.yaml
  module-types/Nokia/PS-7220-IXR-H3-DC-F2B.yaml
Labels: status: accepted

#1199 Add weight information from install guides
  device-types/Nokia/7220-IXR-D1.yaml
  device-types/Nokia/7220-IXR-D2.yaml
  device-types/Nokia/7220-IXR-D2L.yaml
  device-types/Nokia/7220-IXR-D3.yaml
  device-types/Nokia/7220-IXR-D3L.yaml
  device-types/Nokia/7220-IXR-H3.yaml
Labels: status: accepted

#1205 Add Ubiquiti USW-Enterprise-24-PoE
  device-types/Ubiquiti/USW-Enterprise-24-PoE.yaml
Labels: status: accepted

#1202 Add Albis-Elcon BIG 4862
  device-types/Albis-Elcon/BIG2862.yaml
  device-types/Albis-Elcon/BIG4862.yaml
Labels: status: accepted

#1207 Pre-Commit: Add pytest
  .pre-commit-config.yaml
Labels: status: accepted

#1208 Validation Testing Increase
  .github/workflows/validation.yml
  .pre-commit-yamlfmt-config.yaml
  device-types/Cisco/Meraki-M36.yaml
  device-types/Cisco/Meraki-M44.yaml
  device-types/Cisco/Meraki-MR53.yaml
  device-types/Cisco/Meraki-MR53E.yaml
  device-types/Cisco/Meraki-MR56.yaml
  device-types/Cisco/Meraki-MR57.yaml
  device-types/HPE/HP-5120-24G-PoEP-EI.yaml
  device-types/HPE/HP-5120-48G-PoEP-EI.yaml
  device-types/Huawei/S3100-8TP-PWR-EI.yaml
  device-types/Nokia/7220-IXR-D1.yaml
  device-types/Nokia/7220-IXR-D2.yaml
  device-types/Nokia/7220-IXR-D2L.yaml
  device-types/Nokia/7220-IXR-D3.yaml
  device-types/Nokia/7220-IXR-D3L.yaml
  device-types/Nokia/7220-IXR-H3.yaml
  device-types/Ubiquiti/USW-Enterprise-24-PoE.yaml
Labels: status: accepted

#1204 Create TL-SG1016PE
  device-types/TP-Link/TL-SG1016PE.yaml
Labels: status: revisions needed

#1203 Add Synology DS1821+ device type
  device-types/Synology/ds1821+.yaml
Labels: status: accepted

#1212 Add 8-Port Gigabit Ethernet LAN Switch NIM for Cisco ISR
  module-types/Cisco/nim-es2-8.yaml
Labels: status: accepted

#1182 Added several Fortinet device types
  device-types/Fortinet/FG-2200E.yaml
  device-types/Fortinet/FG-2600F.yaml
  device-types/Fortinet/FG-300C.yaml
  device-types/Fortinet/FG-60D.yml
  module-types/Fortinet/SP-FG1800F-PS.yaml
  module-types/Fortinet/SP-FG3800D-PS.yaml
Labels: status: accepted

#1211 Add 16-Port Async Serial NIM for Cisco ISR
  module-types/Cisco/NIM-16A.yaml
Labels: status: accepted

#1225 Adding elevation images folder and test logic
  device-types/Nokia/7220-IXR-H3.yaml
  elevation-images/Nokia/7220-IXR-H3.front.png
  elevation-images/Nokia/7220-IXR-H3.rear.png
  schema/devicetype.json
  tests/definitions_test.py
Labels: status: accepted

#1223 Add TL-SG108PE
  device-types/TP-Link/TL-SG108PE.yaml
Labels: status: accepted

#1219 Add module EX-UM-2x4SFP.yaml
  module-types/Juniper/EX-UM-2x4SFP.yaml
Labels: status: accepted

#1190 Add Ubiquiti INS-3AF-O-G PoE adapter
  device-types/Ubiquiti/INS-3AF-O-G.yaml
Labels: status: accepted

#1241 Added weight and pns to tripp lite
  device-types/Tripp Lite/B064-016.yaml
  device-types/Tripp Lite/B096-016.yaml
  device-types/Tripp Lite/B096-032.yaml
  device-types/Tripp Lite/B097-016.yaml
  device-types/Tripp Lite/PDUMH15AT.yaml
  device-types/Tripp Lite/PDUMH20HVAT.yaml
  device-types/Tripp Lite/SMART1500LCD.yaml
  device-types/Tripp Lite/SMART1500RMXL2UA.yaml
  device-types/Tripp Lite/SMART2200CRMXL.yaml
  device-types/Tripp Lite/ULTRABLOK428.yaml
Labels: status: accepted

#1242 Migrate tripp lite to eaton
  device-types/Eaton/TrippLite-B064-016.yaml
  device-types/Eaton/TrippLite-B096-016.yaml
  device-types/Eaton/TrippLite-B096-032.yaml
  device-types/Eaton/TrippLite-B097-016.yaml
  device-types/Eaton/TrippLite-PDUMH15AT.yaml
  device-types/Eaton/TrippLite-PDUMH20HVAT.yaml
  device-types/Eaton/TrippLite-SMART1500LCD.yaml
  device-types/Eaton/TrippLite-SMART1500RMXL2UA.yaml
  device-types/Eaton/TrippLite-SMART2200CRMXL.yaml
  device-types/Eaton/TrippLite-ULTRABLOK428.yaml
  module-types/Eaton/TrippLite-SNMPWEBCARD.yaml
Labels: status: accepted

#1216 Added Teltonika RUT240 device type
  device-types/Teltonika/RUT240.yaml
Labels: status: accepted

#1237 Create fs-248e-fpoe.yaml
  device-types/FS-248E-FPOE.yaml
Labels: status: accepted

#1245 Added r6515 airflow
  device-types/Dell/PowerEdge_R6515.yaml
Labels: status: accepted

#1246 Allied Telesis AT-MCR12 Update
  device-types/Allied Telesis/AT-MCR12.yaml
Labels: status: accepted

#1247 Eaton Updates
  device-types/Eaton/5PX3000RTN.yaml
  device-types/Eaton/9PX3000iRT2U.yaml
  device-types/Eaton/9PX5KIRTN.yaml
  device-types/Eaton/9PX6K.yaml
  device-types/Eaton/9PXEBM180.yaml
  device-types/Eaton/9PXEBM72RT2U.yaml
  device-types/Eaton/CBL2OUT32.yaml
  device-types/Eaton/EMA107-10.yaml
  device-types/Eaton/EMAT09-10.yml
  device-types/Eaton/ESWB05.yaml
  device-types/Eaton/ESWB22.yaml
  device-types/Eaton/PW103BA1U405.yaml
  device-types/Eaton/Tripp-Lite-B064-016.yaml
  device-types/Eaton/Tripp-Lite-B096-016.yaml
  device-types/Eaton/Tripp-Lite-B096-032.yaml
  device-types/Eaton/Tripp-Lite-B097-016.yaml
  device-types/Eaton/Tripp-Lite-PDUMH15AT.yaml
  device-types/Eaton/Tripp-Lite-PDUMH20HVAT.yaml
  device-types/Eaton/Tripp-Lite-SMART1500LCD.yaml
  device-types/Eaton/Tripp-Lite-SMART1500RMXL2UA.yaml
  device-types/Eaton/Tripp-Lite-SMART2200CRMXL.yaml
  device-types/Eaton/Tripp-Lite-ULTRABLOK428.yaml
Labels: status: accepted

#1248 F5 Bi-IP 2000
  device-types/F5/BIG-IP-2000.yaml
  module-types/F5/SPAFFIV-03G.yaml
Labels: status: accepted

#1249 PA-850 and PAN-PWR-500W-AC
  device-types/Palo Alto/PA-850.yaml
  module-types/Palo Alto/PAN-PWR-500W-AC.yaml
Labels: status: accepted
