Repository netbox-community/devicetype-library, pull requests merged in 2024-10, with the labels that each got.

#1991 Added Fortigate FG-120G, and created front/rear images
  device-types/Fortinet/FG-120G.yaml
  elevation-images/Fortinet/fortinet-fg-120g.front.png
  elevation-images/Fortinet/fortinet-fg-120g.rear.png
Labels: status: accepted

#2310 added device type Dell PowerEdge R350 with elevation images
  device-types/Dell/PowerEdge-R350.yaml
  elevation-images/Dell/dell-poweredge-r350.front.jpg
  elevation-images/Dell/dell-poweredge-r350.rear.jpg
  module-types/Dell/03D09NA00.yaml
Labels: status: revisions needed

#2383 October 2024 Dependency Updates
  .github/workflows/update-generated-schema.yml
  .github/workflows/validation.yml
  device-types/Arista/DCS-7130LBR-48S6QD-R.yaml
  requirements.txt
Labels: dependencies, github_actions

#2384 Create GS324TP.yaml
  device-types/Netgear/GS324TP.yaml
Labels: status: accepted

#2308 Create w1850.yaml
  device-types/Cradlepoint/w1850.yaml
Labels: status: revisions needed

#2286 Add Cisco C2960G-8TC-L
  device-types/Cisco/WS-C2960G-8TC-L.yaml
Labels: status: revisions needed

#2102 Power Sockets
  device-types/Bachmann/Bachmann-6x-power-socket.yml
  device-types/Brennenstuhl/1156057128.yml
  device-types/Rittal/DK-7240-210.yml
  elevation-images/Rittal/rittal-dk-7240-210.front.png
Labels: status: revisions needed

#2112 Add Several FS LIUs
  device-types/FS/FHD-1U-CMP400.yaml
  device-types/FS/FHD-1UFMT-N.yaml
  device-types/FS/FHD-1UFMT-S.yaml
  device-types/FS/FHD-4UFCE.yaml
Labels: status: gathering feedback

#2163 Add Cisco WS-C2960C-8TC-S
  device-types/Cisco/WS-C2960C-8TC-S.yaml
Labels: status: revisions needed

#2209 Add Supermicro SuperServer 1029U-TR4T
  device-types/Supermicro/SYS-1029U-TR4T.yaml
Labels: status: revisions needed

#2245 Added Images for various Juniper EX platform
  device-types/Juniper/EX2300-24MP.yaml
  device-types/Juniper/EX2300-24P.yaml
  device-types/Juniper/EX2300-24T-DC.yaml
  device-types/Juniper/EX2300-24T.yaml
  device-types/Juniper/EX2300-48MP.yaml
  device-types/Juniper/EX2300-48P.yaml
  device-types/Juniper/EX2300-48T.yaml
  device-types/Juniper/EX2300-C-12P.yaml
  device-types/Juniper/EX3400-48P.yaml
  device-types/Juniper/EX3400-48T.yaml
  device-types/Juniper/EX4100-48P.yaml
  device-types/Juniper/EX4100-48T.yaml
  device-types/Juniper/EX4100-F-12P.yaml
  device-types/Juniper/EX4300-24P.yaml
  device-types/Juniper/EX4300-24T.yaml
  device-types/Juniper/EX4300-48MP.yaml
  device-types/Juniper/EX4300-48P.yaml
  device-types/Juniper/EX4400-48F.yaml
  device-types/Juniper/EX4600-40F.yaml
  elevation-images/Juniper/juniper-ex2300-48p.front.png
  elevation-images/Juniper/juniper-ex2300-48p.rear.png
  elevation-images/Juniper/juniper-ex2300-c-12p.front.png
  elevation-images/Juniper/juniper-ex2300-c-12p.rear.png
  elevation-images/Juniper/juniper-ex3400-48p.front.png
  elevation-images/Juniper/juniper-ex3400-48p.rear.png
  elevation-images/Juniper/juniper-ex3400-48t.front.png
  elevation-images/Juniper/juniper-ex3400-48t.rear.png
  elevation-images/Juniper/juniper-ex4100-48p.front.png
  elevation-images/Juniper/juniper-ex4100-48p.rear.png
  elevation-images/Juniper/juniper-ex4100-48t.front.png
  elevation-images/Juniper/juniper-ex4100-48t.rear.png
  elevation-images/Juniper/juniper-ex4100-f-12p.front.png
  elevation-images/Juniper/juniper-ex4100-f-12p.rear.png
  elevation-images/Juniper/juniper-ex4300-24p.front.png
  elevation-images/Juniper/juniper-ex4300-24p.rear.png
  elevation-images/Juniper/juniper-ex4300-24t.front.png
  elevation-images/Juniper/juniper-ex4300-24t.rear.png
  elevation-images/Juniper/juniper-ex4300-48mp.front.png
  elevation-images/Juniper/juniper-ex4300-48p.front.png
  elevation-images/Juniper/juniper-ex4300-48p.rear.png
  elevation-images/Juniper/juniper-ex4400-48f.front.png
  elevation-images/Juniper/juniper-ex4400-48f.rear.png
  elevation-images/Juniper/juniper-ex4600-40f.front.png
  elevation-images/Juniper/juniper-ex4600-40f.rear.png
  elevation-images/Juniper/juniper-ptx10002-36qdd-front.jpg
  elevation-images/Juniper/juniper-ptx10002-36qdd-rear.jpg
Labels: status: accepted

#2378 New Device type: Cudy WR3000 v1
  device-types/Cuda/WR3000-v1.yaml
Labels: status: revisions needed

#2093 Cisco Device: Add C9500X-28C8D
  device-types/Cisco/C9500X-28C8D.yaml
  elevation-images/Cisco/cisco-c9500x-28c8d.front.png
  elevation-images/Cisco/cisco-c9500x-28c8d.rear.png
Labels: status: revisions needed

#2134 Add C9300LM-XXU-4Y switches
  device-types/Cisco/C9300LM-24U-4Y.yaml
  device-types/Cisco/C9300LM-48U-4Y.yaml
Labels: status: revisions needed

#2372 Add deciso dec2700. Pre commit checks passed.
  device-types/Deciso/DEC2750.yaml
  device-types/QNAP/TS-879-pro.yml
Labels: status: revisions needed

#2119 Adding Intel Card, Dell PowerEdge R220 and Extreme Networks x460 48p/t
  device-types/APC/AP8941.yaml
  device-types/Dell/PowerEdge-R220.yml
  device-types/Extreme Networks/X460-48p.yml
  device-types/Extreme Networks/X460-48t.yml
  module-types/Intel/X520-DA2.yaml
Labels: status: revisions needed

#2354 Arctic Wolf AWN1000-10G
  device-types/Arctic-Wolf/awn1000-10g.yaml
Labels: status: revisions needed

#2406 Fix issues with Ciena modules in Windows
  module-types/Ciena/8110-8114-12x25G-sfp28.yaml
  module-types/Ciena/8110-8114-2x400G-cfp2.yaml
  module-types/Ciena/8110-8114-2x400G-qsfpdd-macsec.yaml
  module-types/Ciena/8110-8114-2x400G-qsfpdd.yaml
  module-types/Ciena/8110-8114-8x100G-qsfp28.yaml
  module-types/Ciena/AC-3926-3930-3932-5142.yaml
  module-types/Ciena/AC-3940-3960.yaml
  module-types/Ciena/AC-5162-5170.yaml
  module-types/Ciena/AC-8110-8114.yaml
  module-types/Ciena/AC-8140-8190.yaml
  module-types/Ciena/DC-5162-5170.yaml
  module-types/Ciena/DC-8110-8114.yaml
  module-types/Ciena/DC-8140-8190.yaml
Labels: status: accepted

#2414 add extreme-networks-X440-Series
  device-types/Extreme Networks/X440-24p-10G.yaml
  device-types/Extreme Networks/X440-24p.yaml
  device-types/Extreme Networks/X440-24t-10G.yaml
  device-types/Extreme Networks/X440-24t.yaml
  device-types/Extreme Networks/X440-24tDC.yaml
  device-types/Extreme Networks/X440-24x-10G.yaml
  device-types/Extreme Networks/X440-24x.yaml
  device-types/Extreme Networks/X440-48p-10G.yaml
  device-types/Extreme Networks/X440-48p.yaml
  device-types/Extreme Networks/X440-48t-10G.yaml
  device-types/Extreme Networks/X440-48t.yaml
  device-types/Extreme Networks/X440-48tDC.yaml
  device-types/Extreme Networks/X440-8p.yaml
  device-types/Extreme Networks/X440-8t.yaml
  device-types/Extreme Networks/X440-L2-24t.yaml
  device-types/Extreme Networks/X440-L2-48t.yaml
Labels: status: revisions needed

#2247 Cisco: Add modules, update M5/6
  device-types/Cisco/UCSC-C220-M5SX.yaml
  device-types/Cisco/UCSC-C220-M6S.yaml
  module-types/Cisco/VIC-1455.yaml
  module-types/Cisco/VIC-1457.yaml
  module-types/Cisco/VIC-1467.yaml
  module-types/Cisco/VIC-1477.yaml
  module-types/Cisco/VIC-1495.yaml
  module-types/Cisco/VIC-1497.yaml
  module-types/Cisco/VIC-15235.yaml
  module-types/Cisco/VIC-15237.yaml
  module-types/Cisco/VIC-15238.yaml
  module-types/Cisco/VIC-15425.yaml
  module-types/Cisco/VIC-15427.yaml
  module-types/Cisco/VIC-15428.yaml
Labels: status: revisions needed

#2139 HPE Apollo Chassis with Blade/Sled Servers and module
  device-types/HPE/Apollo-R2000-chassis.yaml
  device-types/HPE/Apollo-R2200-chassis.yaml
  device-types/HPE/Apollo-R2600-chassis.yaml
  device-types/HPE/Apollo-R2800-chassis.yaml
  device-types/HPE/proliant-xl170r-g9-1u.yaml
  device-types/HPE/proliant-xl170r-g9-2u.yaml
  module-types/HPE/Apollo-R2000-RCM-Module.yaml
Labels: status: revisions needed

#2420 add extreme-networks-X450-G2-Series
  device-types/Extreme Networks/X450-G2-24p-10GE4.yaml
  device-types/Extreme Networks/X450-G2-24p-GE4.yaml
  device-types/Extreme Networks/X450-G2-24t-10GE4.yaml
  device-types/Extreme Networks/X450-G2-24t-GE4.yaml
  device-types/Extreme Networks/X450-G2-48p-GE4.yaml
  device-types/Extreme Networks/X450-G2-48t-10GE4.yaml
  device-types/Extreme Networks/X450-G2-48t-GE4.yaml
Labels: status: revisions needed

#2421 add extreme-networks-X460-Series
  device-types/Extreme Networks/X460-24p.yaml
  device-types/Extreme Networks/X460-24t.yaml
  device-types/Extreme Networks/X460-24x.yaml
  device-types/Extreme Networks/X460-48x.yaml
Labels: status: revisions needed

#2135 Dell C6400 Series updates
  device-types/Dell/PowerEdge-C6400.yaml
  device-types/Dell/PowerEdge-C6420.yaml
Labels: status: revisions needed

#2400 Add Meinberg Lantime M1000
  device-types/Meinberg/lantime-m1000.yml
  module-types/Meinberg/IMS-CPU.yml
  module-types/Meinberg/IMS-GNM.yml
  module-types/Meinberg/IMS-GNS-UC.yml
  module-types/Meinberg/IMS-GNS.yml
  module-types/Meinberg/IMS-GPS.yml
  module-types/Meinberg/IMS-GXL.yml
  module-types/Meinberg/IMS-MRI.yml
  module-types/Meinberg/IMS-MSF.yml
  module-types/Meinberg/IMS-PSX210.yml
  module-types/Meinberg/IMS-PWR-AD10.yml
  module-types/Meinberg/IMS-PWR-DC10.yml
  module-types/Meinberg/IMS-PWR-DC20.yml
  module-types/Meinberg/IMS-PZF.yml
  module-types/Meinberg/IMS-TCR.yml
  module-types/Meinberg/IMS-VSG181h.yml
Labels: status: revisions needed

#2431 add extreme-networks-X770-Series
  device-types/Extreme Networks/X770-32q.yaml
Labels: status: accepted

#2430 add extreme-networks-X670-G2-Series
  device-types/Extreme Networks/X670-G2-48x-4q.yaml
  device-types/Extreme Networks/X670-G2-72x.yaml
Labels: status: accepted

#2429 add extreme-networks-X670-Series
  device-types/Extreme Networks/X670-48x.yaml
  device-types/Extreme Networks/X670V-48t.yaml
  device-types/Extreme Networks/X670V-48x.yaml
Labels: status: accepted

#2428 add extreme-networks-X650-Series
  device-types/Extreme Networks/X650-24t.yaml
  device-types/Extreme Networks/X650-24x.yaml
Labels: status: accepted

#2427 add extreme-networks-X480-Series
  device-types/Extreme Networks/X480-24x.yaml
  device-types/Extreme Networks/X480-48t.yaml
  device-types/Extreme Networks/X480-48x.yaml
Labels: status: accepted

#2298 Add Juniper MX304
  device-types/Juniper/MX304-BASE.yaml
  elevation-images/Juniper/juniper-mx304-base.front.png
  elevation-images/Juniper/juniper-mx304-base.rear.png
  module-types/Juniper/MX304-FAN-2RU.yaml
  module-types/Juniper/MX304-LMIC16.yaml
  module-types/Juniper/MX304-PWR2200-AC.yaml
  module-types/Juniper/MX304-PWR2200-DC.yaml
  module-types/Juniper/MX304-PWR2200-HV.yaml
  module-types/Juniper/MX304-RE.yaml
Labels: status: accepted

#2212 Add Cannon imageRUNNER 5XX Series
  device-types/Canon/IR-ADV-525I-III.yaml
  device-types/Canon/IR-ADV-527I.yaml
Labels: status: accepted

#2255 Update FG-40F.yaml
  device-types/Fortinet/FG-40F.yaml
Labels: status: accepted

#2432 add extreme-networks-X460-g2-Series
  device-types/Extreme Networks/X460-G2-16mp-32p-10GE4.yaml
  device-types/Extreme Networks/X460-G2-24p-10GE4.yaml
  device-types/Extreme Networks/X460-G2-24p-24hp-10GE4.yaml
  device-types/Extreme Networks/X460-G2-24p-GE4.yaml
  device-types/Extreme Networks/X460-G2-24t-24ht-10GE4.yaml
  device-types/Extreme Networks/X460-G2-24t-GE4.yaml
  device-types/Extreme Networks/X460-G2-24x-10GE4.yaml
  device-types/Extreme Networks/X460-G2-48p-GE4.yaml
  device-types/Extreme Networks/X460-G2-48t-10GE4.yaml
  device-types/Extreme Networks/X460-G2-48t-GE4.yaml
  device-types/Extreme Networks/X460-G2-48x-10GE4.yaml
Labels: status: accepted

#2207 Add Huawei CE6856-48T6Q-HI
  device-types/Huawei/CE6856-48T6Q-HI.yaml
Labels: status: revisions needed

#2240 Add Meinberg IMS LANTIME M1000
  device-types/Meinberg/lantime-m1000.yml
  elevation-images/Meinberg/meinberg-lantime-m1000.front.png
  elevation-images/Meinberg/meinberg-lantime-m1000.rear.png
Labels: status: revisions needed

#2437 add extreme-networks-elevation-images-x150-series
  device-types/Extreme Networks/X150-24p.yaml
  device-types/Extreme Networks/X150-24t.yaml
  device-types/Extreme Networks/X150-48t.yaml
  elevation-images/Extreme Networks/extreme-networks-x150-24p.front.png
  elevation-images/Extreme Networks/extreme-networks-x150-24t.front.png
  elevation-images/Extreme Networks/extreme-networks-x150-48t.front.png
Labels: status: revisions needed
