Repository netbox-community/devicetype-library, pull requests merged in 2025-02, with the labels that each got.

#2710 Fix: Remove rear-port declarations from Minisforum MS-01 (#2709)
  device-types/Minisforum/Minisforum-MS-01.yml
Labels: status: accepted

#2736 Add multiple Cisco Catalyst devices
  device-types/Cisco/WS-C2960-24-S.yaml
  device-types/Cisco/WS-C2960-24LC-S.yaml
  device-types/Cisco/WS-C2960-48PST-L.yaml
  device-types/Cisco/WS-C2960-48TT-S.yaml
  device-types/Cisco/WS-C2960S-48TS-S.yaml
  device-types/Cisco/WS-C3560X-24T-L.yaml
  device-types/Cisco/WS-C3560X-48T-L.yaml
  device-types/Cisco/WS-C3650-48TQ-L.yaml
  device-types/Cisco/WS-C4507R-E.yaml
Labels: status: revisions needed

#2763 added kemp-lm-x1 device
  device-types/Kemp Technologies/LM-X1.yaml
  elevation-images/Kemp Technologies/kemp-technologies-lm-x1.front.png
Labels: status: revisions needed

#2747 Create softline_sl911.yaml
  device-types/Softline/sl911.yaml
Labels: status: revisions needed

#2791 Arista DCS-7280SE-68-F
  device-types/Arista/DCS-7280SE-68-F.yaml
  elevation-images/Arista/arista-dcs-7280se-68-f.front.jpg
  elevation-images/Arista/arista-dcs-7280se-68-f.rear.png
Labels: status: revisions needed

#2831 Create storeever-msl6480.yaml
  device-types/HPE/StoreEver-MSL6480.yaml
Labels: status: revisions needed

#2820 Update Tripp-Lite-N054-024.yaml
  device-types/Eaton/Tripp-Lite-N054-024.yaml
Labels: status: gathering feedback

#2821 Update Tripp-Lite-B051-000.yaml
  device-types/Eaton/Tripp-Lite-B051-000.yaml
Labels: status: gathering feedback

#2768 Add Dell Poweredge R530 + R540 elevation images
  elevation-images/Dell/dell-poweredge-R530.front.jpg
  elevation-images/Dell/dell-poweredge-R530.rear.jpg
  elevation-images/Dell/dell-poweredge-R540.front.jpg
  elevation-images/Dell/dell-poweredge-R540.rear.jpg
Labels: status: revisions needed
